### ISSUE TITLE
What is the purpose of MultiDevFailed?

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-idl#7]
At least in JTango it is simply converted to DevFailed and then is propagated to the client. Maybe we can just remove it and use DevFailed everywhere instead?

**Comment by bourtemb** [comment]
In C++, this seems to be used when a client is invoking write_attributes() for instance.
It is very useful to get the list of exceptions occurring with the name of the attribute associated with each exception.

**Comment by Ingvord** [comment]
And what if some of attributes did not fail? The whole request is considered to be failed?!

I think this is wrong assumption. In REST when client reads bunch of attributes the request never fails, it simply returns an array where some of the elements may have errors. I guess _DeviceAttribute#hasFailed_ has the same meaning i.e. multiple read must return an array and never fail due to a single attribute failure. DevFailed may be thrown though e.g. in case of timeout, or device is not reachable (I would throw specific exception, but that is a different story). So my conclusion (if MultiDevFailed is only for this purpose) is to remove it and guarantee the behavior described above.

Anyway the proper way to handle it is to propagate to the client not to hide behind DevFailed (in JTango) => compile time incompatability

**Comment by bourtemb** [comment]
MultiDevFailed is used in the case of the write_attributes, not read_attributes.

**Comment by Ingvord** [comment]
Well, I do not see the big difference, still we have to have a response

**Comment by bourtemb** [comment]
What do you mean?
write_attributes() is returning void or throwing an exception if at least one attribute could not be written.
In this case, the MultiDevFailed exception informs the client that some of the attributes could not be written and is giving precise information on the different exceptions thrown when trying to write the attributes which could not be written, including the name of these attributes which failed.

**Comment by Ingvord** [comment]
I mean **void** must be replaced with an array where some attributes are good, somes have failed.

I tend to this solution (as we break compatibility anyway), because it feels unnatural to throw exception in non-exceptional situation (we do multiplexed request and expect a multiplexed response). Plus as far as I understand there might be a situation when some of the attributes have been updated already (e.g. we write 3 attributes, first 2 pass the 3rd has failed - we throw an exception), if so (I have not looked through the code to proof it) existing solution is error prone, consider a lazy programmer:

```
try{
   device.writeAttributes(attrs);
} catch (MultiDevFailed ex){
    //just do it again
    /* Oops, we might have badly written device attributes with side effects on writing, and they will be updated again */
}
```

**Comment by bourtemb** [comment]
What do you mean we break compatibility anyway??
Do you remember the presentations we made, saying compatibility will be preserved all along the way?
Source code compatibility will be preserved as best effort. Best effort means we will try to preserve it as much as possible. This is a good example where I don't see why we would change it...

It feels completely natural for write_attributes() to throw an exception when at least one attribute could not be written. This is an unexpected behaviour since the user wanted to write all the attributes. The write failed for some of them, so this is an error case. It seems natural to throw an exception in this case.
The user can then react to this exception and do what is appropriate depending on what attributes failed.
It is of course the programmer's responsibility to handle this case properly depending on the use case.
I don't buy the lazy programmer argument because the programmer has currently the same amount of information available as in your proposal. And the lazy programmer actually does not need to verify one by one that all the individual write_attribute succeeded in the current situation. So the current situation is actually better for a lazy programmer when the call succeeds ;-)...

I would not change the write_attributes() behaviour.
Returning nothing when all the attributes could be written does not seem unnatural to me.
If the call succeeds, this means all the attributes have been written. As simple as that.
Nothing prevents you to implement something on top of that in the REST API to give more detailed results to the web client, listing all the attributes which have been written if one feels this is more appropriate for a REST API.

**Comment by Ingvord** [comment]
Well, In this particular case we can not preserve compatibility, look at JTango PR [#48](https://github.com/tango-controls/JTango/pull/48). Specifically [this](https://github.com/tango-controls/JTango/pull/48/files#diff-d51517d2c0470997fd6f274d46a67e57) diff

We have to propagate it to the client -> methods signature has changed -> no source code compatibility anymore

I mean what is currently done is definitely wrong, because it fails in both scenarios (we throw exception or not)

**Comment by Ingvord** [comment]
Well _lazy programmer_ argument is indeed inaccurate here.

But still you are talking about flow control using exceptions:

```
try{
  device.write_attributes(attrs);
}catch(MultiDevFailed ex){
  for(ex.errors){/*do smth*/}
}
```

Which is considered as a bad practice (see [this](http://wiki.c2.com/?DontUseExceptionsForFlowControl) or _Effective Java 2nd edition Item 57_ or chapter 9 in general)

Apart from dirty code, in Java creating an exception is simply a very heavy operation, look at these numbers [here](https://www.slideshare.net/AndreiPangin/down-to-stack-traces-up-from-heap-dumps/6?src=clipshare)

So the better way (in Java) is to have it like this:

```
DeviceAttribute[] response = device.write_attributes(attr);

response.filter(it -> it.hasFailed()).forEach(/*do smth*/)
```

Client library may decide to throw an exception in this case. Or the client might be an intermediate server which just wants to pass the result some where else.

Compatibility will be preserved via an additional library i.e. jtango-client-legacy maven artifact on-top of new jtango

**Comment by bourtemb** [comment]
I have the feeling you are mixing the things here.
We are talking about write_attributes() case here. This method as it is now does not return anything (return void) when everything goes well and it returns an exception when something bad happens.
I don't think this is considered as a bad practice.
The examples given in your first link have nothing to do with what we are currently doing.
We are not using exceptions as flow control. We are using exceptions to report a problem which is the purpose of an exception.
write_attributes does not return anything because there is no value to be returned in case of success. The solution you are proposing is very similar to what would have been done for a C program with return codes. I don't think this is considered as good practice in object oriented languages.
I also don't buy the argument "Creating an exception is simply a very heavy operation". When there is a problem while writing one of several attributes during the write_attributes() call, we need to report the error which occurred to the user. The user needs to get the details about what has failed and the best way for this is to get a full detailed exception for every attributes which has failed. The exception will have to be created anyway because the user might need it, unless you are planning to simply remove the exception and let the user blind without any clue about why writing some attributes failed.
I also don't understand why we would need to return a DeviceAttribute array in the specific case of write_attributes().
It looks like you are mixing the read_attributes() case and the write_attributes() case. They are completely different cases.

**Comment by Ingvord** [comment]
Yeah, looks like I am mixing smth, but not read_/write_

What I have failed to explain (my bad) is that I am talking about low-level API.

So if we want speak OO then I am imaging a class sole purpose of which is to deliver a message e.g. 

```
interface TangoProtocol {
  Response readAttributes(TangoMessage msg) throws IOException, TangoProtocolException;
  Response writeAttributes(TangoMessage msg) throws IOException, TangoProtocolException;
  //...
}
```

It knows nothing about the semantic of the message, and exceptional situations for this class are, for instance, network failure, or protocol error (incorrect message). Therefore it should not throw any exceptions in case the message has been delivered and response acquired.

Then on  top of this class we have Device API:

```
interface Device {
  // DevFailed basically wraps exceptions from underlying layer
  DeviceAttribute[] readAttributes(attrs) throws DevFailed /*, MultiDevFailed - missing in current API*/;
  void writeAttributes(attrs) throws DevFailed, MultiDevFailed;
}
```

OR

```
interface Device {
  DeviceAttribute[] readAttributes(attrs) throws DevFailed;
  //return all DeviceAttributes, some of them hasFailed some has actual value from the server
  DeviceAttribute[] writeAttributes(attrs) throws DevFailed;
}
```

OR

```
interface Device {
  DeviceAttribute[] readAttributes(attrs) throws DevFailed;
  //return failed DeviceAttributes only
  FailedDeviceAttribute[] writeAttributes(attrs) throws DevFailed;
}
```

Here are 3 variants of how I would define Device API in this case. 

1. Is what we have now. I do not like it, because it is not consistent: read_attributes must also throw MultiDevFailed then??? This is obviously a bad decision, because client may and up failing to read any of the attributes. So existing approach is quite OK (return an array that represents the result of the remote execution). Let's make it consistent with the Device API, we have to change _write_ semantic for this...

2. The most generic approach - DevFailed is thrown only in case of serious failure (Device is not reachable, network error  etc); _write_ returns actual values from the device (good for GUIs BTW, as they now can update view with the exact values returned from the device)

3. We may return a list of failed attributes

This Device API in its turn is an intermediate layer, there are other clients on top of it.

So I tend to propagate the decision about whether failed write is an exception or not to the end client and not take over this decision on the lower levels. This also make API easier to learn, as there are only few main points to remember:

 - DevFailed - catastrophy
 - result must be processed (and it is always done in the same manner)

Some of the client library may decide to throw an exception - this is fine. It is their decision. Some may not.

> The solution you are proposing is very similar to what would have been done for a C program with return codes. I don't think this is considered as good practice in object oriented languages.

This is not true. It is not an error code - we return sophisticated data structure, analyzing which client decides what to do.

**Comment by Ingvord** [comment]
Forget about MultiDevFailed for now, as @bourtemb suggested we can use __-nofinal__ IDL compiler key and not to change JTango code
